#!/usr/bin/env python3
"""
Script to generate example READMEs using read-you.
This helps maintain up-to-date examples of what the tool can generate.
"""

import os
import sys
from pathlib import Path

# Add the parent directory to Python path so we can import the main module
sys.path.append(str(Path(__file__).parent.parent))

from src.readme_generator import ReadmeGenerator

def generate_self_readme():
    """Generate a README for read-you itself."""
    print("Generating self-README example...")
    
    # Initialize the generator
    generator = ReadmeGenerator()
    
    # Get the project root directory
    root_dir = Path(__file__).parent.parent
    
    # Generate the README content
    content = generator.generate_readme(str(root_dir), verbose=True)
    
    # Prepare the example README
    header = """# read-you (Self-Generated README)

> This README was automatically generated by running read-you on its own codebase. 
> It shows what the tool generates without human editing.

```bash
uvx --with-editable . read-you . --verbose
```

Below is the unedited output:

---
"""
    
    # Write to the example file
    example_path = root_dir / 'examples' / 'self-generated' / 'README.md'
    example_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(example_path, 'w', encoding='utf-8') as f:
        f.write(header + '\n' + content)
    
    print(f"Example README generated at: {example_path}")

if __name__ == '__main__':
    generate_self_readme()
